In [1]:
# Assignment One
# Course: MIS 5150
# Professor: Dr. David Paper

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Question 1:
# 
import tensorflow as tf
import numpy as np

# a.
# Creating dataset
data_set = tf.data.Dataset.from_tensor_slices([[0, 1, 9, 8, 7, 3], [2, 9, 4, 0, 2, 3], [7, 3, 3, 2, 2, 1], [0, 0, 1, 2, 2, 5]])

# b.
# Iterating data
# method 1
for elements in data_set:
  print(elements)
print('')
# method 2
for elements in data_set:
  print(elements.numpy())
print('')
# method 3
iterator = iter(data_set)
print(iterator.get_next())
print(iterator.get_next())
print(iterator.get_next())
print(iterator.get_next())
print('')
# method 4
for data in data_set:
    print (data.numpy())
print('')

# c.
# display 3rd element from 2nd tensor
# method 1
ls = []
for item in data_set:
  e = item.numpy()
  ls.append(e)
print('3rd element from 2nd tensor:',ls[1][2])
print('')
# method 2
np_arr = np.asarray(ls, dtype=np.float32)
print('3rd element from 2nd tensor:',int(np_arr[1][2]))
print('')
# method 3
display_element = np.array([[0, 1, 9, 8, 7, 3], [2, 9, 4, 0, 2, 3], [7, 3, 3, 2, 2, 1], [0, 0, 1, 2, 2, 5]])
print('3rd element from 2nd tensor:', display_element[1][2])

tf.Tensor([0 1 9 8 7 3], shape=(6,), dtype=int32)
tf.Tensor([2 9 4 0 2 3], shape=(6,), dtype=int32)
tf.Tensor([7 3 3 2 2 1], shape=(6,), dtype=int32)
tf.Tensor([0 0 1 2 2 5], shape=(6,), dtype=int32)

[0 1 9 8 7 3]
[2 9 4 0 2 3]
[7 3 3 2 2 1]
[0 0 1 2 2 5]

tf.Tensor([0 1 9 8 7 3], shape=(6,), dtype=int32)
tf.Tensor([2 9 4 0 2 3], shape=(6,), dtype=int32)
tf.Tensor([7 3 3 2 2 1], shape=(6,), dtype=int32)
tf.Tensor([0 0 1 2 2 5], shape=(6,), dtype=int32)

[0 1 9 8 7 3]
[2 9 4 0 2 3]
[7 3 3 2 2 1]
[0 0 1 2 2 5]

3rd element from 2nd tensor: 4

3rd element from 2nd tensor: 4

3rd element from 2nd tensor: 4


In [3]:
# Question 2:
# 
import tensorflow as tf
# GPU Enable
tf.__version__, tf.test.gpu_device_name()


# output ('2.4.1', '/device:GPU:0')

('2.5.0-dev20210312', '')

In [4]:
# Question 3:
# 
import tensorflow as tf
import pandas as pd
from tensorflow import keras

ds = 'flag.data'
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/flags/flag.data'
dataset_path = tf.keras.utils.get_file(ds, url)
# downloaded the data using keras
dataset_path

# cols from the flag.names file
cols = ['name','landmass','zone','area','population','language','religion','bars','stripes','colours','red','green','blue','gold','white','black','orange','mainhue','circles','crosses','saltires','quarters','sunstars','crescent','triangle','icon','animate','text','topleft','botright']

# raw dataset using pandas
raw_dataset = pd.read_csv(dataset_path, names=cols)

# displaying dataset
raw_dataset.head()

# remove non numerical values
raw_dataset.pop('name')
raw_dataset.pop('mainhue')
raw_dataset.pop('topleft')
raw_dataset.pop('botright')
# print to check removal of non-numerical values
raw_dataset.head()

# step 2
dataset = tf.data.Dataset.from_tensor_slices(raw_dataset.values)

# range for dataset
dataset = tf.data.Dataset.range(10)

# using take function
for i in dataset.take(3):
  print(i)
print('')

16384/15240 [================================] - 0s 5us/step
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)



In [5]:
# Question 4:
# 
import tensorflow as tf

# a. create a tensor
dataset = tf.data.Dataset.range(10)

# b. display the tendor
for row in dataset:
  print(row)
print('')

# c. repeat and batch
data_batch = dataset.repeat(5).batch(4)

# d. display batched sensor
for row in data_batch:
  print(row)
print('')

# e. map to cube the dataset
data_map = data_batch.map(lambda x:x ** 3)

# f. batched tensor display
for item in data_map.take(2):
  print(item)
print('')

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([8 9 0 1], shape=(4,), dtype=int64)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([8 9 0 1], shape=(4,), dtype=int64)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([8 9], shape=(2,), dtype=int64)

tf.Tensor([ 0  1  8 27], shape=(4,), dtype=i

In [6]:
# Question 5:
# 
import tensorflow as tf

# a. create dataset
dataset = tf.data.Dataset.range(10).repeat(5)
print ('dataset has', len(list(dataset)), 'elements')
print('')

# b. dataset buffer and display
ds = dataset.shuffle(buffer_size=5).batch(7)

for item in ds:
  print(item)
print('')

dataset has 50 elements

tf.Tensor([3 2 0 4 7 6 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 8 4 6 1], shape=(7,), dtype=int64)
tf.Tensor([8 9 9 5 7 3 2], shape=(7,), dtype=int64)
tf.Tensor([5 5 1 0 6 4 8], shape=(7,), dtype=int64)
tf.Tensor([7 2 1 3 0 4 9], shape=(7,), dtype=int64)
tf.Tensor([9 8 1 5 7 3 6], shape=(7,), dtype=int64)
tf.Tensor([5 6 7 8 4 0 2], shape=(7,), dtype=int64)
tf.Tensor([9], shape=(1,), dtype=int64)

